name: Tag Redis Driver

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Test Redis driver
      run: |
        cd invalidation/drivers/redis
        go test -v ./...
    
    - name: Create and push Redis driver tag
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git tag invalidation/drivers/redis/${{ inputs.tag }}
        git push origin invalidation/drivers/redis/${{ inputs.tag }}

